// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0nLG0RtG_z0YS2T7TrPbgabL2Nvb6Ts',
    appId: '1:728416083842:web:dfe08bc2a888793aac399b',
    messagingSenderId: '728416083842',
    projectId: 'order-tracking-app-b9ca3',
    authDomain: 'order-tracking-app-b9ca3.firebaseapp.com',
    storageBucket: 'order-tracking-app-b9ca3.appspot.com',
    measurementId: 'G-QJ277VQTLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQGZKGBPU0iRDGdkNvbfU1KfFa5iGbXt8',
    appId: '1:728416083842:android:d5a20237c632cee3ac399b',
    messagingSenderId: '728416083842',
    projectId: 'order-tracking-app-b9ca3',
    storageBucket: 'order-tracking-app-b9ca3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJXwuYVTtvXYVOU7AypEgT0n4uSYvigHM',
    appId: '1:728416083842:ios:ad7ec506d310509bac399b',
    messagingSenderId: '728416083842',
    projectId: 'order-tracking-app-b9ca3',
    storageBucket: 'order-tracking-app-b9ca3.appspot.com',
    iosBundleId: 'com.example.orderTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJXwuYVTtvXYVOU7AypEgT0n4uSYvigHM',
    appId: '1:728416083842:ios:ad7ec506d310509bac399b',
    messagingSenderId: '728416083842',
    projectId: 'order-tracking-app-b9ca3',
    storageBucket: 'order-tracking-app-b9ca3.appspot.com',
    iosBundleId: 'com.example.orderTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz0nLG0RtG_z0YS2T7TrPbgabL2Nvb6Ts',
    appId: '1:728416083842:web:c87ff611f05b5229ac399b',
    messagingSenderId: '728416083842',
    projectId: 'order-tracking-app-b9ca3',
    authDomain: 'order-tracking-app-b9ca3.firebaseapp.com',
    storageBucket: 'order-tracking-app-b9ca3.appspot.com',
    measurementId: 'G-SC2S4ELTR8',
  );
}
